// generates ML-derived cluster centroids from a sample of normies.
// writes the result to src/lib/cluster/centroids.ts.
//
// run: pnpm cluster-normies
//
// takes ~7 min at the default sample size (200 normies, 2 API calls each).
// set CLUSTER_SAMPLE env var to a smaller number for a quick test run.

import { writeFileSync } from "fs";
import { join } from "path";
import { kmeans } from "ml-kmeans";
import { normies } from "../src/lib/normies/api";
import { density as calcDensity, distribution as calcDist } from "../src/lib/normies/analyze";
import { archetype as calcArchetype } from "../src/lib/normies/archetypes";
import type { Traits } from "../src/lib/normies/types";

const MAX_TOKEN_ID = 9999;
const K = 8;
const SAMPLE = parseInt(process.env.CLUSTER_SAMPLE ?? "200", 10);
const CONCURRENCY = 5;
const DELAY_MS = 1200; // stay under 60 req/min with 2 calls per normie × 5 concurrent

function buildVector(pixels: string, traits: Traits): number[] {
  const d = calcDensity(pixels);
  const dist = calcDist(pixels);
  const arch = calcArchetype(traits, d, dist);
  return [
    d,
    dist.topMass,
    dist.bottomMass,
    dist.centerMass,
    dist.edgeMass,
    arch.category === "human" ? 1 : 0,
    arch.category === "cat" ? 1 : 0,
    arch.category === "alien" ? 1 : 0,
    arch.category === "agent" ? 1 : 0,
    arch.formality === "formal" ? 1 : 0,
    arch.formality === "casual" ? 1 : 0,
    arch.formality === "experimental" ? 1 : 0,
    arch.formality === "eccentric" ? 1 : 0,
    arch.energy === "reserved" ? 1 : 0,
    arch.energy === "baseline" ? 1 : 0,
    arch.energy === "expressive" ? 1 : 0,
  ];
}

async function fetchOne(tokenId: number): Promise<number[] | null> {
  try {
    const [pixels, traits] = await Promise.all([
      normies.pixels(tokenId),
      normies.traits(tokenId),
    ]);
    return buildVector(pixels, traits);
  } catch {
    return null;
  }
}

async function processBatch(ids: number[]): Promise<number[][]> {
  const results = await Promise.allSettled(ids.map(fetchOne));
  return results.flatMap((r) =>
    r.status === "fulfilled" && r.value !== null ? [r.value] : [],
  );
}

async function main() {
  // evenly spaced sample across 0..MAX_TOKEN_ID
  const step = Math.floor(MAX_TOKEN_ID / SAMPLE);
  const ids = Array.from({ length: SAMPLE }, (_, i) => i * step);

  console.log(`sampling ${ids.length} normies (every ${step}th) in batches of ${CONCURRENCY}`);

  const vectors: number[][] = [];
  for (let i = 0; i < ids.length; i += CONCURRENCY) {
    const batch = ids.slice(i, i + CONCURRENCY);
    const batchVectors = await processBatch(batch);
    vectors.push(...batchVectors);
    process.stdout.write(`\r  ${vectors.length} / ${ids.length} collected`);
    if (i + CONCURRENCY < ids.length) await new Promise((r) => setTimeout(r, DELAY_MS));
  }
  console.log(`\ncollected ${vectors.length} feature vectors`);

  if (vectors.length < K) {
    console.error(`not enough data (need at least ${K} samples). try a larger CLUSTER_SAMPLE.`);
    process.exit(1);
  }

  console.log(`running k-means with K=${K}...`);
  const result = kmeans(vectors, K, { initialization: "kmeans++", maxIterations: 300 });
  const centroids = result.centroids;

  const labels = [
    "entropy management",
    "strategic continuity",
    "distributed operations",
    "pattern recognition services",
    "client experience",
    "emergent technologies",
    "organizational development",
    "creative infrastructure",
  ];

  const out = `// generated by scripts/cluster-normies.ts — do not edit manually.
// sample size: ${vectors.length} normies, K=${K}, seed: kmeans++
//
// feature vector layout (16 dims):
// [density, topMass, bottomMass, centerMass, edgeMass,
//  cat_human, cat_cat, cat_alien, cat_agent,
//  form_formal, form_casual, form_experimental, form_eccentric,
//  energy_reserved, energy_baseline, energy_expressive]

export const CENTROIDS: number[][] = [
${centroids.map((c, i) => `  // ${i}: ${labels[i] ?? "cluster " + i}\n  [${c.map((v) => v.toFixed(6)).join(", ")}]`).join(",\n")}
];
`;

  const outPath = join(__dirname, "../src/lib/cluster/centroids.ts");
  writeFileSync(outPath, out, "utf8");
  console.log(`wrote centroids to ${outPath}`);

  // print cluster summary
  const assignments = vectors.map((v) => {
    let best = 0, bestDist = Infinity;
    centroids.forEach((c, i) => {
      const d = Math.sqrt(c.reduce((s, cv, j) => s + (cv - v[j]) ** 2, 0));
      if (d < bestDist) { bestDist = d; best = i; }
    });
    return best;
  });
  const counts = Array(K).fill(0);
  assignments.forEach((a) => counts[a]++);
  console.log("\ncluster sizes:");
  counts.forEach((n, i) => console.log(`  ${i} (${labels[i] ?? "?"}): ${n}`));
}

main().catch((e) => { console.error(e); process.exit(1); });
