import Link from "next/link";
import { AGENCY_URL } from "@/lib/site";

export function Footer() {
  return (
    <footer className="mt-auto border-t border-border">
      <div className="mx-auto flex max-w-5xl flex-col gap-6 px-5 py-10 sm:flex-row sm:items-end sm:justify-between sm:px-8">
        <div className="space-y-1.5">
          <p className="font-pixel-square text-sm text-foreground">ARPI Lab</p>
          <p className="max-w-xs text-[13px] leading-relaxed text-muted-foreground">
            Attribute-Rooted Personality Inference. Personality is computed from
            attributes, not generated by a language model.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-5">
          <Link
            href="/methodology"
            className="font-mono text-[12px] text-muted-foreground transition-colors hover:text-foreground"
          >
            methodology
          </Link>
          <Link
            href="/research"
            className="font-mono text-[12px] text-muted-foreground transition-colors hover:text-foreground"
          >
            research
          </Link>
          <a
            href={AGENCY_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="font-mono text-[12px] text-muted-foreground transition-colors hover:text-foreground"
          >
            the employment agency ↗
          </a>
        </div>
      </div>
    </footer>
  );
}
