// generated by scripts/cluster-normies.ts — run `pnpm cluster-normies` to replace with ML-derived centroids.
//
// feature vector layout (16 dims):
// [density, topMass, bottomMass, centerMass, edgeMass,
//  cat_human, cat_cat, cat_alien, cat_agent,
//  form_formal, form_casual, form_experimental, form_eccentric,
//  energy_reserved, energy_baseline, energy_expressive]

export const CENTROIDS: number[][] = [
  // 0: entropy management — expressive + eccentric + edge mass
  [0.40, 0.45, 0.55, 0.40, 0.60, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
  // 1: strategic continuity — reserved + formal + low density
  [0.20, 0.50, 0.50, 0.55, 0.45, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
  // 2: distributed operations — baseline + casual + edge mass
  [0.30, 0.48, 0.52, 0.30, 0.70, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  // 3: pattern recognition — baseline + formal + center mass + dense
  [0.50, 0.50, 0.50, 0.65, 0.35, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
  // 4: client experience — baseline + casual + center mass
  [0.30, 0.50, 0.50, 0.60, 0.40, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
  // 5: emergent technologies — expressive + experimental
  [0.45, 0.50, 0.50, 0.50, 0.50, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
  // 6: organizational development — reserved + formal + mid density + top-heavy
  [0.35, 0.58, 0.42, 0.55, 0.45, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
  // 7: creative infrastructure — expressive + casual + bottom-heavy
  [0.45, 0.35, 0.65, 0.45, 0.55, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
];
